version: "3.8"

services:
  client-prod:
    container_name: prod-client-cms-xsd
    image: ${IMAGE_APP_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=api-xosodinh.apibet.site
      - NEXT_PUBLIC_API_WS=ws-xosodinh.apibet.site
      - NEXT_PUBLIC_TELEGRAM_TOKEN=7823816631:AAFFOvzHiMAAn9zjc0UrZh_OYrrUvASwjGk
      - NEXT_PUBLIC_TELEGRAM_CHAT_ID=-1002386997983
      - NEXT_PUBLIC_NODE_ENV=production
    ports:
      - "3022:3000"
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4

