version: "3.8"

services:
  client-dev:
    container_name: dev-client-cms-xsd
    image: ${IMAGE_APP_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV_ENVIROMENT=dev
      - NEXT_PUBLIC_API_URL=
      - NEXT_PUBLIC_SITE_URL=
      - NEXT_TELEMETRY_DEBUG=0
    ports:
      - "3021:3000"
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4